//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.19 at 11:30:35 AM BST 
//


package Examples;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Lending complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Lending">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="lendid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="customerID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="periodOfRent" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dateOfStart" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="dateOfEnd" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Lending", propOrder = {
    "lendid",
    "customerID",
    "periodOfRent",
    "dateOfStart",
    "dateOfEnd"
})
public class Lending {

    @XmlElement(required = true)
    protected String lendid;
    @XmlElement(required = true)
    protected String customerID;
    @XmlElement(required = true)
    protected String periodOfRent;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateOfStart;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateOfEnd;

    /**
     * Gets the value of the lendid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLendid() {
        return lendid;
    }

    /**
     * Sets the value of the lendid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLendid(String value) {
        this.lendid = value;
    }

    /**
     * Gets the value of the customerID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerID() {
        return customerID;
    }

    /**
     * Sets the value of the customerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerID(String value) {
        this.customerID = value;
    }

    /**
     * Gets the value of the periodOfRent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeriodOfRent() {
        return periodOfRent;
    }

    /**
     * Sets the value of the periodOfRent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeriodOfRent(String value) {
        this.periodOfRent = value;
    }

    /**
     * Gets the value of the dateOfStart property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateOfStart() {
        return dateOfStart;
    }

    /**
     * Sets the value of the dateOfStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateOfStart(XMLGregorianCalendar value) {
        this.dateOfStart = value;
    }

    /**
     * Gets the value of the dateOfEnd property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateOfEnd() {
        return dateOfEnd;
    }

    /**
     * Sets the value of the dateOfEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateOfEnd(XMLGregorianCalendar value) {
        this.dateOfEnd = value;
    }

}
